#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Backend/main.py
from __future__ import annotations

import os
import time
import warnings
from collections.abc import Callable

from fastapi import Depends, FastAPI, Request, status
from fastapi.exceptions import RequestValidationError
from loguru import logger
from prometheus_client import Counter, Histogram, make_asgi_app
from starlette.exceptions import HTTPException as StarletteHTTPException
from starlette.responses import JSONResponse

from api.routers import claims, customers, health, reports, upload
from core.exceptions import ConflictError, NotFoundError, UnprocessableEntityError, InternalServerError
from core.logging import setup_logging
from core.security import require_api_key
from schemas.response import ErrorResponse


# serialization warning when with_structured_output() is used.
_ = warnings.filterwarnings("ignore", message="Pydantic serializer warnings")


_ = setup_logging()


# Initiakize fastapi app
app = FastAPI(
    title="ClaimMesh Backend API",
    description="Insurance claims ingestion, search, and reporting API.",
    version="1.0.0",
)


# Grab the container ID generated by Docker/K8s
POD_ID = os.getenv("HOSTNAME", "standalone-node")


# 1. Define Custom Metrics for Core Analytics (IP, Locale, Endpoint)
api_request_counter = Counter(
    name="api_requests_total",
    documentation="Total count of incoming API requests",
    labelnames=["endpoint", "method", "status_code", "node_id"],
    unit="1",
)

api_latency_histogram = Histogram(
    name="api_request_duration_seconds",
    documentation="API execution latency distribution",
    labelnames=["endpoint", "node_id"],
    unit="s",
)


# Expose internal Prometheus metrics screen directly to the scrape runner
metrics_app = make_asgi_app()
app.mount("/metrics", metrics_app)


@app.middleware("http")
async def request_telemetry_middleware(request: Request, call_next: Callable):
    """
    Logs every request (method/path/status/latency, no bodies/PII) and records
    Prometheus metrics, excluding /health and /metrics to avoid scrape-loop noise.
    """
    path  = request.url.path
    paths = ("/metrics", "/metrics/", "/health", "/health/")

    # Exclude metrics endpoint from scraping recursion loops
    if path in paths:
        return await call_next(request)

    st  = time.perf_counter()
    res = await call_next(request)
    dt  = time.perf_counter() - st

    logger.info(f"{request.method} {path} -> {res.status_code} ({dt * 1000:.1f}ms)")

    # Increment lean counters at the end of the request execution
    _ = api_request_counter.labels(
        endpoint=path,
        method=request.method,
        status_code=str(res.status_code),
        node_id=POD_ID,
    ).inc()

    _ = api_latency_histogram.labels(
        endpoint=path,
        node_id=POD_ID
    ).observe(dt)

    return res


@app.exception_handler(UnprocessableEntityError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    return JSONResponse(
        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
        content=ErrorResponse(
            error="ValidationError",
            message=str(exc.errors()),
        ).model_dump(),
    )


@app.exception_handler(NotFoundError)
async def not_found_handler(request: Request, exc: NotFoundError):
    return JSONResponse(
        status_code=status.HTTP_404_NOT_FOUND,
        content=ErrorResponse(
            error="NotFoundError",
            message=exc.error,
        ).model_dump(),
    )


@app.exception_handler(ConflictError)
async def conflict_handler(request: Request, exc: ConflictError):
    return JSONResponse(
        status_code=status.HTTP_409_CONFLICT,
        content=ErrorResponse(
            error="ConflictError",
            message=exc.error,
        ).model_dump(),
    )


@app.exception_handler(StarletteHTTPException)
async def http_exception_handler(request: Request, exc: StarletteHTTPException):
    return JSONResponse(
        status_code=exc.status_code,
        content=ErrorResponse(
            error=type(exc).__name__,
            message=str(exc.detail),
        ).model_dump(),
    )


@app.exception_handler(InternalServerError)
async def unhandled_exception_handler(request: Request, exc: Exception):
    logger.exception(f"Unhandled exception on {request.url.path}: {exc}")
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content=ErrorResponse(
            error="InternalServerError",
            message="An unexpected error occurred",
        ).model_dump(),
    )


app.include_router(health.router)
app.include_router(upload.router, dependencies=[Depends(require_api_key)])
app.include_router(claims.router, dependencies=[Depends(require_api_key)])
app.include_router(customers.router, dependencies=[Depends(require_api_key)])
app.include_router(reports.router, dependencies=[Depends(require_api_key)])
