global:
  scrape_interval: 5s # Increased from 2s to reduce unnecessary frequency locally

scrape_configs:
  - job_name: "fastapi-backend"
    metrics_path: "/metrics/"
    dns_sd_configs:
      - names:
          - "backend"
        type: "A"
        port: 8000
