"""initial tables

Revision ID: efb28469585d
Revises: 
Create Date: 2026-07-05 20:40:58.668985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efb28469585d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.SmallInteger(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('is_potential_fraud', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('age >= 0 AND age <= 130', name=op.f('ck_customers_ck_customers_age_range')),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_customers'))
    )
    op.create_table('upload_audits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset', sa.String(length=20), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('inserted', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload_audits'))
    )
    op.create_table('policies',
    sa.Column('policy_id', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('policy_issue_date', sa.Date(), nullable=False),
    sa.Column('coverage_limit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deductible', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('coverage_limit >= 0', name=op.f('ck_policies_ck_policies_coverage_limit_nonneg')),
    sa.CheckConstraint('deductible >= 0', name=op.f('ck_policies_ck_policies_deductible_nonneg')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_policies_customer_id_customers')),
    sa.PrimaryKeyConstraint('policy_id', name=op.f('pk_policies'))
    )
    op.create_index('idx_policies_customer_id', 'policies', ['customer_id'], unique=False)
    op.create_table('claims',
    sa.Column('claim_id', sa.String(length=20), nullable=False),
    sa.Column('policy_id', sa.String(length=20), nullable=False),
    sa.Column('loss_date', sa.Date(), nullable=False),
    sa.Column('loss_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cause', sa.String(length=100), nullable=False),
    sa.Column('payout_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='valid', nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('loss_amount >= 0', name=op.f('ck_claims_ck_claims_loss_amount_nonneg')),
    sa.CheckConstraint('payout_amount >= 0', name=op.f('ck_claims_ck_claims_payout_amount_nonneg')),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.policy_id'], name=op.f('fk_claims_policy_id_policies')),
    sa.PrimaryKeyConstraint('claim_id', name=op.f('pk_claims'))
    )
    op.create_index('idx_claims_cause', 'claims', ['cause'], unique=False)
    op.create_index('idx_claims_loss_date', 'claims', ['loss_date'], unique=False)
    op.create_index('idx_claims_policy_id', 'claims', ['policy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_claims_policy_id', table_name='claims')
    op.drop_index('idx_claims_loss_date', table_name='claims')
    op.drop_index('idx_claims_cause', table_name='claims')
    op.drop_table('claims')
    op.drop_index('idx_policies_customer_id', table_name='policies')
    op.drop_table('policies')
    op.drop_table('upload_audits')
    op.drop_table('customers')
    # ### end Alembic commands ###
